
GET http://localhost:5000/api/v1/permissions

### GET

GET http://localhost:5000/api/v1/faculty/major

###

GET http://localhost:5000/api/v1/majors

### GET
# 
GET http://localhost:5000/api/v1/roles

### GET

GET http://localhost:5000/api/v1/roles/permission

### DELETE

//kalau mau delete cabut dulu permision ID
DELETE http://localhost:5000/api/v1/role/2dca3d77-fcfa-47cf-bdc8-20bdb1327e03
  

### POST 

POST http://localhost:5000/api/v1/role
Content-Type: application/json

{
    "roleName": "Administrator",
    "description": "Full access to all system features and settings",
    "rolePermission": {
        "create": [
            { "permissionId": "85f8df38-8541-4b96-aa5d-1a03040ea80f" }
        ]
    }
}


### PATCH

PATCH http://localhost:5000/api/v1/role/10310b0d-8d76-4156-89d7-76d2a5120af6
Content-Type: application/json

{
    "rolePermission": {
        "delete": [
            {
                "permissionId": "85f8df38-8541-4b96-aa5d-1a03040ea80f"
            }
        ]
    }
}